//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OperatingRoomEntities : DbContext
    {
        public OperatingRoomEntities()
            : base("name=OperatingRoomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<@class> @class { get; set; }
        public virtual DbSet<deviceForSurgery> deviceForSurgery { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<scheduling> scheduling { get; set; }
        public virtual DbSet<specialDevice> specialDevice { get; set; }
        public virtual DbSet<surgery> surgery { get; set; }
        public virtual DbSet<user> user { get; set; }


        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }




    }
}
