//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduling
    {
        public int schedulingCode { get; set; }
        public System.DateTime schedulingDate { get; set; }
        public System.TimeSpan schedulingHour { get; set; }
        public int idRoom { get; set; }
        public int surgeryCode { get; set; }
    
        public virtual room room { get; set; }
        public virtual surgery surgery { get; set; }
    }
}
